### ISSUE TITLE
Not able to use for custom url (organization)

### ISSUE THREAD

**Issue by kubadotka** [Gyumeijie/github-files-fetcher#5]
I was trying to use tool with my company's custom url (github.company.com) and I am getting following error: 'Invalid domain: github.com is expected!'
Is there a way to use different domain instead of the one default?

I used syntax: 
fetcher --auth=username:password --url="https://github.company.com/repo/path/tree/master/subfolder" --out="~/output_folder"

**Comment by kubadotka** [comment]
I've found the clause in file index.js:
`  if (hostname !== 'github.com') {
    throw new Error('Invalid domain: github.com is expected!');
  }`

I bet it's the only thing I would need to change, but I am not familiar with js at all.

**Comment by Gyumeijie** [comment]
@kubadotka, I'm sorry, the `github-files-fetcher` can only fetch files from github.com, because it used and must obey the APIs provided by github.
