### ISSUE TITLE
Depreciation of OutgoingMessage.prototype._headers causes failures

### ISSUE THREAD

**Issue by CollinChaffin** [Gyumeijie/github-files-fetcher#6]
Files no longer fully complete with this error:

`authenticated: false(node:11524) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated`

**Comment by Gyumeijie** [comment]
@CollinChaffin, sorry I can't reproduce this issue with my environment: Mac OS,  Node 11.14.0 and NPM 6.7.0, and therefore I can't solve this problem by now; Could you change your Node version to check whether it can work by doing that.
